ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.vimrc ~/.config/nvim/init.vim
ln -s ~/dotfiles/i3/config ~/.config/i3/config
ln -s ~/dotfiles/git/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.termiterc ~/.config/termite/config
ln -s ~/dotfiles/.Xresources ~/.Xresources
ln -s ~/dotfiles/.Xresources ~/.Xdefaults
ln -s ~/dotfiles/xmonad/xmonad.hs ~/.xmonad/xmonad.hs
ln -s ~/dotfiles/xmonad/.xmobarrc ~/.xmonad/.xmobarrc
