sudo: false
language: c
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- stack setup --upgrade-cabal
- stack install gtk2hs-buildtools

addons:
  apt:
    packages:
    - libgmp-dev
    - libgtk2.0-dev
    - libcairo2-dev
    - libglib2.0-dev
matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.2

script:
 - stack --no-terminal --system-ghc build
